### ISSUE TITLE
Database (Test)

### ISSUE THREAD

**Issue by ArchWand** [ArchWand/1984Bot#2]
Rules, blacklist, reaction roles and such should be stored in a database, not hard-coded.

I know dino will probably get to it soon, but I just wanted an excuse to use the issues

**Comment by Fnige** [comment]
I wonder if this pings the webhook

**Comment by dinolord919** [comment]
That's the plan; I hard-coded those two rules just for testing purposes. It'll probably stay that way until I've added the edit and remove commands for the rules, since then it'll actually be functional enough to warrant proper saving.

**Comment by ArchWand** [comment]
think it's prolly time to close this
