### ISSUE TITLE
Is this a tuple?

### ISSUE THREAD

**Issue by ArchWand** [ArchWand/1984Bot#22]
>```py
>    shoelaceChannel = bot.get_channel(shoelaceID)
>    if message.channel == shoelaceChannel:
>        for pair in newMemberKeys:
>            if message.author.id == pair[0]:
>                if message.content == str(pair[1]):

@dinolord919 Is `pair` a tuple? If it is, I can write this a bit more concisely.

**Comment by dinolord919** [comment]
Yep. Could pretty easily go if [message.author.id, int(message.content)] == pair or something like that. I'll be reviewing things later tonight, so you've got plenty of time to do whatever, by the way.
